tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=15,score_TalkTime=15] ["",{"text":"<"},{"text":"Xana","color":"light_purple"},{"text":"> ♪¡Y yo soy Xana! ¡Encantada!♪ "}]
tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=20,score_TalkTime=20] ["",{"text":"<"},{"text":"Xana","color":"light_purple"},{"text":"> Hemos venido a buscarte, ¿sabes?"}]
tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=27,score_TalkTime=27] ["",{"text":"<"},{"text":"Serena","color":"gold"},{"text":"> Aquí, en la región de Kalos, vive el Profesor Ciprés, que es un erudito de los Pokémon muy reconocido."}]
tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=3,score_TalkTime=3] ["",{"text":"<"},{"text":"...","color":"gold"},{"text":"> ¡Bienvenido al pueblo!"}]
tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=34,score_TalkTime=34] ["",{"text":"<"},{"text":"Serena","color":"gold"},{"text":"> Pues bien, el profesor nos ha pedido ayuda a cinco chicos."}]
tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=42,score_TalkTime=42] ["",{"text":"<"},{"text":"Serena","color":"gold"},{"text":"> ¡Como lo oyes! Lo que me tiene intrigada es cómo puede haber oído hablar de ti, que te acabas de mudar a Pueblo Boceto..."}]
tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=52,score_TalkTime=52] ["",{"text":"<"},{"text":"Xana","color":"light_purple"},{"text":"> Oye, de momento, ¿por qué no vamos tirando para el pueblo de al lado?"}]
tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=60,score_TalkTime=60] ["",{"text":"<"},{"text":"Xana","color":"light_purple"},{"text":"> ¡Así podremos conseguir nuestros Pokémon!"}]
tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=65,score_TalkTime=65] ["",{"text":"<"},{"text":"Xana","color":"light_purple"},{"text":"> ¡Me muero de ganas de ver al mío! ¡Síii! ¡Venga! ¡A toda pastilla!"}]
tellraw @s[score_DialogueTrigger_min=2,score_DialogueTrigger=2,tag=!Dialogue2,score_TalkTime_min=7,score_TalkTime=7] ["",{"text":"<"},{"text":"Serena","color":"gold"},{"text":"> Me llamo Serena y vivo en la casa de al lado. ¡Somos vecinos!"}]
tellraw @s[score_DialogueTrigger_min=1,score_DialogueTrigger=1,tag=!Dialogue1,score_TalkTime_min=15,score_TalkTime=15] {"text":"<Madre> ¡Casa nueva, vida nueva! "}
tellraw @s[score_DialogueTrigger_min=1,score_DialogueTrigger=1,tag=!Dialogue1,score_TalkTime_min=2,score_TalkTime=2] ["",{"text":"<Madre> ¡Buenos días, "},{"selector":"@s"},{"text":"!"}]
tellraw @s[score_DialogueTrigger_min=1,score_DialogueTrigger=1,tag=!Dialogue1,score_TalkTime_min=20,score_TalkTime=20] {"text":"<Madre> ¿Qué tal si empiezas por ir a saludar a los vecinos?"}
tellraw @s[score_DialogueTrigger_min=1,score_DialogueTrigger=1,tag=!Dialogue1,score_TalkTime_min=7,score_TalkTime=7] {"text":"<Madre> Parece que has descansado bien después del trajín de ayer con la mudanza, ¿eh?"}
