tag @s add FlyVaniville
tag @s add FlyKiloude
tag @s add FlyAquacorde
tag @s add FlySantalune
tag @s add FlySnowbelle
tag @s add FlyCouriway
tag @s add FlyAnistar
tag @s add FlyDendemille
tag @s add FlyPokemonLeague
tag @s add FlyLumiose
tag @s add FlyLaverre
tag @s add FlyAmbrette
tag @s add FlyCamphrier
tag @s add FlyCyllage
tag @s add FlyGeosenge
tag @s add FlyShalour
tag @s add FlyCoumarine
